# Generated by Django 4.2.1 on 2023-05-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nfts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nft",
            name="url",
            field=models.CharField(default="/", max_length=1024),
        ),
        migrations.AlterField(
            model_name="nft",
            name="owner",
            field=models.CharField(default="Ilya", max_length=512),
        ),
        migrations.AlterField(
            model_name="nft",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="nft",
            name="size",
            field=models.IntegerField(default=0),
        ),
    ]
