# Generated by Django 4.2.1 on 2023-05-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nfts", "0002_nft_url_alter_nft_owner_alter_nft_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nft",
            name="size",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterModelTable(
            name="nft",
            table="nfts",
        ),
    ]
